//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoBimbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int id { get; set; }
        public Nullable<int> Semana { get; set; }
        public Nullable<int> Agencia_ID { get; set; }
        public Nullable<int> Canal_ID { get; set; }
        public Nullable<int> Ruta_SAK { get; set; }
        public Nullable<int> Cliente_ID { get; set; }
        public Nullable<int> Producto_ID { get; set; }
    }
}
