//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoBimbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class train
    {
        public int Semana { get; set; }
        public int Agencia_ID { get; set; }
        public int Canal_ID { get; set; }
        public int Ruta_SAK { get; set; }
        public int Cliente_ID { get; set; }
        public int Producto_ID { get; set; }
        public int Venta_uni_hoy { get; set; }
        public decimal Venta_hoy { get; set; }
        public int Dev_uni_proxima { get; set; }
        public decimal Dev_proxima { get; set; }
        public int Demanda_uni_equil { get; set; }
    }
}
